version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  web:
    build: .
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./expense_tracker:/usr/src/app
      - ./poetry.lock:/usr/src/poetry.lock
      - ./pyproject.toml:/usr/src/pyproject.lock
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PROJECT_FOLDER=/app
